  export const careerThemes = [
    {
    id: "meg_i_kontekst",
    title: {
      no: "Meg i kontekst",
      en: "",
      ar: "",
      fa: "",
      ku: "",
      so: "",
      es: "",
      sw: "",
      ta: "",
      ti: "",
      tr: "",
      uk: "",
      ur: "",
    },
    subthemes: [
      {
        id: "introduksjon",
        title: {
          no: "Introduksjon",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "nye_ord",
        title: {
          no: "Nye ord",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "egenskaper",
        title: {
          no: "Egenskaper",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave_1",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "interesser",
        title: {
          no: "Interesser",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppgave",
        title: {
          no: "Oppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "verdier",
        title: {
          no: "Verdier",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave_2",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "roller",
        title: {
          no: "Roller",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppsummering",
        title: {
          no: "Oppsummering",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
    ],
  },

  {
    id: "muligheter_og_begrensninger",
    title: {
      no: "Muligheter og begrensninger",
      en: "",
      ar: "",
      fa: "",
      ku: "",
      so: "",
      es: "",
      sw: "",
      ta: "",
      ti: "",
      tr: "",
      uk: "",
      ur: "",
    },
    subthemes: [
      {
        id: "introduksjon",
        title: {
          no: "Introduksjon",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "nye_ord",
        title: {
          no: "Nye ord",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "mulighetshorisont",
        title: {
          no: "Mulighetshorisont",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "begrensninger",
        title: {
          no: "Begrensninger",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "tankefeller",
        title: {
          no: "Tankefeller",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "religion",
        title: {
          no: "Religion",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppsummering",
        title: {
          no: "Oppsummering",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
    ],
  },

  {
    id: "valg_og_tilfeldigheter",
    title: {
      no: "Valg og tilfeldigheter",
      en: "",
      ar: "",
      fa: "",
      ku: "",
      so: "",
      es: "",
      sw: "",
      ta: "",
      ti: "",
      tr: "",
      uk: "",
      ur: "",
    },
    subthemes: [
      {
        id: "introduksjon",
        title: {
          no: "Introduksjon",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "nye_ord",
        title: {
          no: "Nye ord",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "egne_valg",
        title: {
          no: "Egne valg",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case_1",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "gode_tilfeldigheter",
        title: {
          no: "Gode tilfeldigheter",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case_2",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppsummering",
        title: {
          no: "Oppsummering",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
    ],
  },

  {
    id: "tilpasning_og_motstand",
    title: {
      no: "Tilpasning og motstand",
      en: "Adaptation and Resistance",
      ar: "",
      fa: "",
      ku: "",
      so: "",
      es: "",
      sw: "",
      ta: "",
      ti: "",
      tr: "",
      uk: "",
      ur: "",
    },
    subthemes: [
      {
        id: "introduksjon",
        title: {
          no: "Introduksjon",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "nye_ord",
        title: {
          no: "Nye ord",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppsummering",
        title: {
          no: "Oppsummering",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
    ],
  },

  {
    id: "endring_og_stabilitet",
    title: {
      no: "Endring og stabilitet",
      en: "",
      ar: "",
      fa: "",
      ku: "",
      so: "",
      es: "",
      sw: "",
      ta: "",
      ti: "",
      tr: "",
      uk: "",
      ur: "",
    },
    subthemes: [
      {
        id: "introduksjon",
        title: {
          no: "Introduksjon",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "nye_ord",
        title: {
          no: "Nye ord",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "endring",
        title: {
          no: "Endring",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "stabilitet",
        title: {
          no: "Stabilitet",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "case",
        title: {
          no: "Case",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "refleksjonsoppgave",
        title: {
          no: "Refleksjonsoppgave",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
      {
        id: "oppsummering",
        title: {
          no: "Oppsummering",
          en: "",
          ar: "",
          fa: "",
          ku: "",
          so: "",
          es: "",
          sw: "",
          ta: "",
          ti: "",
          tr: "",
          uk: "",
          ur: "",
        },
      },
    ],
  },
 ];