/* 
Countries and their languagecodes:
    Norway: no
    English: en
    Arabic: ar
    Farsi: fa
    Kurmanji: ku
    Somali: so
    Spanish: es
    Swahili: sw
    Tamil: ta
    Tigrinya: ti
    Turkish: tr
    Ukrainian: uk
    Urdu: ur
*/
export const healthThemes = [
    {
        id: "skeiv_verden",
        title: {
            no: "Skeiv verden",
            en: "Queer world",
            ar: "",
            fa: "",
            ku: "",
            so: "",
            es: "",
            sw: "",
            ta: "",
            ti: "",
            tr: "",
            uk: "",
            ur: "",

        },
        subthemes: [
            {
                id: "valgfrihet",
                title: {
                    no: "Valgfrihet",
                    en: "Freedom of choice",
                    ar: "حرية الاختيار",
                    fa: "آزادی انتخاب",
                    ku: "Azadiya hilbijartinê",
                    so: "Xorriyada-doorashada",
                    es: "La Libertad de Elección",
                    sw: "Uhuru wa kuchagua",
                    ta: "",
                    ti: "ናይ ምምራጽ ናጽነት",
                    tr: "Tercih Özgürlüğü",
                    uk: "Свобода вибору",
                    ur: "اختیار کا حق", 
                }
            }, {
                id: "sosiale_normer",
                title: {
                    no: "Sosiale normer",
                    en: "Social norms",
                    ar: "الأعراف الاجتماعية",
                    fa: "نورم‌های اجتماعی",
                    ku: "Adatên civakî",
                    so: "Xeerarka Bulshada",
                    es: "Normas sociales",
                    sw: "Kanuni za kijamii",
                    ta: "",
                    ti: "ማሕበራዊ ስርዓታት",
                    tr: "Sosyal normlar",
                    uk: "Соціальні норми",
                    ur: "معاشرتی اصول", 
                }
            }, {
                id: "mangfold",
                title: {
                    no: "Mangfold",
                    en: "Diversity",
                    ar: "التنوع",
                    fa: "تنوع",
                    ku: "Pir-rengî",
                    so: "Kala duwanaansho",
                    es: "La Diversidad",
                    sw: "Kutafautiana",
                    ta: "",
                    ti: "ብዙሕነት (ፍልልይነት)",
                    tr: "Toplumsal Çeşitlilik",
                    uk: "Різноманітність",
                    ur: "تنوع",
            }
        }, {
                id: "diskriminering",
                title: {
                    no: "Diskriminring",
                    en: "Discrimination",
                    ar: "التمييز العنصري",
                    fa: "تبعیض",
                    ku: "Cudakarî",
                    so: "Takoorid (Kala eexasho)",
                    es: "La Discriminación",
                    sw: "Ubaguzi",
                    ta: "",
                    ti: "ምግላል",
                    tr: "Ayrımcılık",
                    uk: "Дискримінація",
                    ur: "امتیازی سلوک",
            }
        }
        ]
    },
    {
        id: "vold_i_nare_relasjoner",
        title: {
            no: "Vold i nære relasjoner",
            en: "",
            ar: "",
            fa: "",
            ku: "",
            so: "",
            es: "",
            sw: "", 
            ta: "",
            ti: "",
            tr: "",
            uk: "",
            ur: "",
        },
        subthemes: [
            {
                id: "vold_introduksjon",
                title: {
                    no: "Introduksjon",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "vold_nye_ord", // vi må muligens finne en bedre løsning på id-navn, da mange av de samme ordene går igjen i flere temaer. Kanskje id kan være en kombinasjon av tema og ord som skrevet nå, slik at det blir unikt?
                title: {
                    no: "Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "typer_vold",
                title: {
                    no: "Typer vold",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "naere_relasjoner",
                title: {
                    no: "Nære relasjoner",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "avvergingsplikt",
                title: {
                    no: "Avvergingsplikt",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "taushetsplikt",
                title: {
                    no: "Taushetsplikt",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "tegn_paa_vold",
                title: {
                    no: "Tegn på vold",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "hvem_kan_hjelpe_1",
                title: {
                    no: "Hvem kan hjelpe, 1",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "hvem_kan_hjelpe_2",
                title: {
                    no: "Hvem kan hjelpe, 2",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }, 
            {
                id: "vold_case",
                title: {
                    no: "Case",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "", 
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }
        ]
    },
    {
        id: "mat_og_helse",
        title: {
            no: "Mat og helse",
            en: "",
            ar: "",
            fa: "",
            ku: "",
            so: "",
            es: "",
            sw: "", 
            ta: "",
            ti: "",
            tr: "",
            uk: "",
            ur: "",
        },
        subthemes: [
            {
                id: "mat_og_helse_introduksjon",
                title: {
                    no: "Introduksjon",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_2_1",
                title: {
                    no: "2.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_matkultur",
                title: {
                    no: "2.2 Matkultur",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_3_1",
                title: {
                    no: "3.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_naering_i_mat_del_1",
                title: {
                    no: "3.2 Næring i mat, del 1",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_4_1",
                title: {
                    no: "4.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_naering_i_mat_del_2",
                title: {
                    no: "4.2 Næring i mat, del 2",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_5_1",
                title: {
                    no: "5.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_frukt_og_gront",
                title: {
                    no: "5.2 Frukt og grønt",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_6_1",
                title: {
                    no: "6.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_unnga_sukker",
                title: {
                    no: "6.2 Unngå sukker",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_case_1",
                title: {
                    no: "Case",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_8_1",
                title: {
                    no: "8.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_diabetes",
                title: {
                    no: "8.2 Diabetes",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_9_1",
                title: {
                    no: "9.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_munnhelse",
                title: {
                    no: "9.2 Munnhelse",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_10_1",
                title: {
                    no: "10.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_matfett",
                title: {
                    no: "10.2 Matfett",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_11_1",
                title: {
                    no: "11.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_sjomat",
                title: {
                    no: "11.2 Sjømat",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_melkeprodukter",
                title: {
                    no: "Melkeprodukter",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_korn",
                title: {
                    no: "Korn",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_14_1",
                title: {
                    no: "14.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_salt",
                title: {
                    no: "14.2 Salt",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_nye_ord_15_1",
                title: {
                    no: "15.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_hygiene",
                title: {
                    no: "15.2 Hygiene",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_case_2",
                title: {
                    no: "Case",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "mat_og_helse_oppsummering",
                title: {
                    no: "Oppsummering",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }
        ]
    },
    {
        id: "fysisk_aktivitet",
        title: {
            no: "Fysisk aktivitet",
            en: "",
            ar: "",
            fa: "",
            ku: "",
            so: "",
            es: "",
            sw: "",
            ta: "",
            ti: "",
            tr: "",
            uk: "",
            ur: "",
        },
        subthemes: [
            {
                id: "fysisk_aktivitet_introduksjon",
                title: {
                    no: "Introduksjon",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_2_1",
                title: {
                    no: "2.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_vaer_fysisk_aktiv",
                title: {
                    no: "2.2 Vær fysisk aktiv",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_3_1",
                title: {
                    no: "3.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_intensivtrening",
                title: {
                    no: "3.2 Intensivtrening",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_4_1",
                title: {
                    no: "4.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_styrketrening",
                title: {
                    no: "4.2 Styrketrening",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_5_1",
                title: {
                    no: "5.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_energiinntak_og_energiforbruk",
                title: {
                    no: "5.2 Energiinntak og energiforbruk",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_6_1",
                title: {
                    no: "6.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_blodsukker",
                title: {
                    no: "6.2 Blodsukker",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_7_1",
                title: {
                    no: "7.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_kolesterol",
                title: {
                    no: "7.2 Kolesterol",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_8_1",
                title: {
                    no: "8.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_blodtrykk",
                title: {
                    no: "8.2 Blodtrykk",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_9_1",
                title: {
                    no: "9.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_kreft",
                title: {
                    no: "9.2 Kreft",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_10_1",
                title: {
                    no: "10.1  Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_hjernen",
                title: {
                    no: "10.2 Hjernen",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_11_1",
                title: {
                    no: "11.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_smerte",
                title: {
                    no: "11.2 Smerte",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_nye_ord_12_1",
                title: {
                    no: "12.1 Nye ord",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_muskler_og_skjelett",
                title: {
                    no: "12.2 Muskler og skjelett",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_andre_aspekter",
                title: {
                    no: "13. Andre aspekter",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_caser",
                title: {
                    no: "14. Caser",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "fysisk_aktivitet_oppsummering",
                title: {
                    no: "Oppsummering",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }
        ]
        // her skal PSYKISK HELSE ligge, men usikker på strukturen pga undertemaene, så ventet med å legge det inn.
    },
    {
        id: "kvinnens_reproduktive_helse",
        title: {
            no: "Kvinnens reproduktive helse",
            en: "",
            ar: "",
            fa: "",
            ku: "",
            so: "",
            es: "",
            sw: "",
            ta: "",
            ti: "",
            tr: "",
            uk: "",
            ur: "",
        },
        subthemes: [
            {
                id: "kvinnens_reproduktive_helse_ytre_kjonnsorganer",
                title: {
                    no: "Kvinnens ytre kjønnsorganer",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "kvinnens_reproduktive_helse_indre_kjonnsorganer",
                title: {
                    no: "Kvinnens indre kjønnsorganer",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "kvinnens_reproduktive_helse_menstruasjon",
                title: {
                    no: "Menstruasjon",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            },
            {
                id: "kvinnens_reproduktive_helse_prevensjon",
                title: {
                    no: "Prevensjon",
                    en: "",
                    ar: "",
                    fa: "",
                    ku: "",
                    so: "",
                    es: "",
                    sw: "",
                    ta: "",
                    ti: "",
                    tr: "",
                    uk: "",
                    ur: "",
                }
            }
        ]
    }
]
